logging:
  level:
    root: INFO
    "[org.springframework]": INFO
    "[org.mongodb]": INFO
    "[io.symphony]": DEBUG
    "[org.springframework.cloud]": INFO
    "[org.springframework.amqp]": INFO

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  cloud:
    stream:
      function:
        definition: publishPoint;processCommand
      bindings:
        publishPoint-out-0:
          destination: status
        processCommand-in-0:
          destination: command
      rabbit:
        bindings:
          publishPoint-out-0:
            producer:
              exchangeType: fanout
          processCommand-in-0:
            consumer:
              exchangeType: fanout

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      defaults:
        enabled: false
      prometheus:
        enabled: true

symphony:
  demo:
    name: demo
    points:
      - id: demo1
        type: Quantity
        labels:
          foo: bar
        name: name1
        value: "5.6 °C"
        access:
          - READ
          - WRITE
      - id: demo2
        type: Switch
        labels:
          foo: bar
        name: name2
        access:
          - READ
      - id: demo3
        type: Switch
        labels:
          bar: foo
        name: name3
        access:
          - READ
          - WRITE